name: Deploy to Dev environment

jobs:
#   Build docker image
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Extract project version
        id: extract_version
        run: |
          echo "VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
          echo "VERSION=${{ steps.extract_version.outputs.VERSION }}"

# Perform the jobs when the CI workflow for the develop branch is successful
on:
  workflow_run:
    workflows: ["Develop Branch CI"]
    types:
      - completed
